### ISSUE TITLE
Support for different project names

### ISSUE THREAD

**Issue by kap** [mduft/lcdsl#1]
We often have the problem, that a project will be copied (or branched) with it's launch configurations. 
This new projects get's a new project name.
After the copy and renaming of the project the launch configurations they will not longer work, because they contain the old project name. 

It would be nice to have a place holder for the project which will be filled with the current project.
Especially for launch configurations located in the project it would be helpful.

**Comment by mduft** [comment]
I suggest two ways to achieve this, ideally implementing both of them:
 * explicit with "project self;"
 * implicit by just not specifying a project at all
I will look into this...

**Comment by mduft** [comment]
I went for the "project self;" solution. This has some benefits over the "default if it is not present" solution:
 * it makes the self reference explicitly visible
 * it makes the implementation of the language simpler
