### ISSUE TITLE
Cannot add two plugins with same id but different version

### ISSUE THREAD

**Issue by enikao** [mduft/lcdsl#26]
I'd like to add the same plugin twice, with different versions.
This is possible in regular launch configs.

LcDsl gives an error `Duplicate PluginWithVersion 'org.antlr.runtime'`

Example:
````
plugin org.antlr.runtime 3.2.0.v201101311130;
plugin org.antlr.runtime 4.3.0.v201502022030;
````

**Comment by mduft** [comment]
Thanks for reporting. This is definitely a bug. However you should be able to work around it by adding a "proxy" bundle to your workspace, which has no content, just the two "Require-Bundle"s for the two versions, and add that in the launch configuration instead.

**Comment by enikao** [comment]
Thanks for the hint. However, I only need this to work around issues in the auto-resolving, not my own plugins. Thus, I don't want to maintain additional artifacts.

Specifically:
* Xtext needs org.antlr.runtime 3.2, Sirius needs 4.3
* E4 needs org.apache.batik.css 1.6, several others 1.10

**Comment by mduft** [comment]
Understood. Whilst I do want to fix this bug of course, you can still work around the issues with a single bundle with dependencies to all the doubled-up-dependencies. Nobody needs to actually use that bundle, it is just there to tear in additional dependencies that are impossible to declare with this bug.

**Comment by enikao** [comment]
Yes, the _real_ issue is the auto-resolver who does not understand this constraint and adds only the newest version (for both regular and LcDsl launch configs, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=472778).

**Comment by mduft** [comment]
Well, we do have dependencies to multiple guava versions transitively in our application, and LcDsl is able to generate launch configuration which contain both versions. We do NOT use the same resolver as Eclipse itself. I actually proposed a patch for the resolver a while ago. AFAIK the most current Eclipse has a different fix for the issue.

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=489319

Re-reading the upstream bug: do you have simpleconfigurator checked in your launch configuration?

**Comment by enikao** [comment]
What is simpleconfigurator? Maybe I looked up the wrong bug.

Your remark on resolver might explain another issue I have: My launch config behaves differently whether I run it via the menu bar or via the launch configs dialog. I didn't report it yet because my project is not yet available for you to look into (will change soon; it's a newer version of https://github.com/altran-mde/xtext-sirius-integration).

**Comment by mduft** [comment]
Simpleconfigurator is a simple implementation of a OSGi framework configurator which defines which bundles should be loaded by the runtime. It uses a bundles.info file which is generated if simpleconfigurator is used. Unfortunately it seems that Eclipse still defaults to using the ULTRA-legacy UpdateManager instead of P2 (the current mechanism for bundle management in RCP applications) which was used in very old Eclipse versions and does not /really/ know OSGi that well - especially duplicate bundles with just version difference don't work with it, even if the bundles are checked in the launch configuration.

**Comment by enikao** [comment]
Where do I choose the simpleconfigurator? I checked the launch config dialog and the preferences, and didn't find any hint.

**Comment by mduft** [comment]
Simply add the org.eclipse.equinox.simpleconfigurator (or so, from the top of my head) bundle to your launch configuration, or as dependency of your software.

**Comment by enikao** [comment]
doesn't really help; after clicking on "add required plugins" (in a regular launch config):

![image](https://user-images.githubusercontent.com/2211690/59511641-1f7dac80-8eb7-11e9-86cd-df9a703d4d81.png)
