### ISSUE TITLE
new feature: Link to products / features / plugins

### ISSUE THREAD

**Issue by enikao** [mduft/lcdsl#27]
I'd like to jump to the referenced product / feature / plugin when Ctrl-clicking / pressing F3 on a reference.

Example (`|` = cursor position):
````
plugin com.example.m|y.plugin;
````
Pressing F3 should open `plugin.xml` in `com.example.my.plugin`.

**Comment by mduft** [comment]
Best would be to open the MANIFEST.MF - you can access plugin.xml from there anyway. plugin.xml might not always exist...

**Comment by enikao** [comment]
I agree, MANIFEST.MF is the right target. Essentially the same functionality as currently exists in feature editor to jump to included. plugins.

**Comment by mduft** [comment]
Right now, links to paths/plug-ins and faetures are supported. Products and applications are on a little bit different page, but finding the way to the plug-in which /defines/ the product/application anyway should help a lot already.
