### ISSUE TITLE
new feature: Add required dependencies

### ISSUE THREAD

**Issue by enikao** [mduft/lcdsl#29]
It would be nice to have a quickfix that adds all required dependencies to a launch config.

This could work
* For a complete launch config (main use case)
* For one entry (product / feature / plugin) to only add the dependencies required for this one

In any case, we should add transitive dependencies, too.

**Comment by mduft** [comment]
This is actually the default with LcDsl. You don't have to declare all dependencies. Just declare the entry point bundle. LcDsl will figure out the dependencies on it's own. Usually, all our (in my case) launch configurations contain a single 'plugin' directive. The rest is 'application', 'workspace-dir', etc.

**Comment by enikao** [comment]
Yes, I'm aware of the default behavior.

This feature would write the resulting list into the launch config. That's useful for debugging, and also to fix issues with the auto-resolver (see #26).

**Comment by mduft** [comment]
Its not exactly what you wanted, but there now is an action on a launch configuration which will pop up a dialog listing all resolved plugin dependencies in lcdsl syntax (for copy & paste).
