### ISSUE TITLE
Easy access to raw launch configuration file

### ISSUE THREAD

**Issue by aaiezza** [mduft/lcdsl#31]
Perhaps via the right‑click menu, a selection for bringing up the XML file for the launch configuration in the Eclipse editor.
For this, I could see a `Open` and `Open With` similar to that if you right‑click a file in the Project Explorer.

It's sometimes nice to be able to edit those files outright as oppose to needing to work through the Launch Configuration Editor GUI window.

Additionally with this, a separate context‑menu selection for opening the location of the launch configuration in the file navigator (Windows Explorer (win), Finder (macOS), etc.) would be really nice to have as well.
`Open File Location`

**Comment by mduft** [comment]
I took some time to look into this closely. There are some technical aspects to this which makes it hard to achieve what you request.

1. There are local and non-local launch configurations in Eclipse, the logic to actually find the correct file/location of a launch configuration is not as straight forward as I would have wished for.
2. The API on the launch configuration view does not allow access to the ILaunchConfiguration, as different providers might not even be based on Eclipse ILaunchConfiguration, but may provide a totally different mechanism to launch/control...

Thus I will have to reject the request for the moment, but will make sure to re-visit as the API evolves.
