### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [mduft/lcdsl#33]
Hello Launch Configuration DSL team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Launch Configuration DSL project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by mduft** [comment]
Sure thing, thats nice :)

```
<tr>
	<td><a href="https://github.com/mduft/lcdsl">Launch Configuration DSL (LcDsl)</a></td>
	<td>LcDsl provides a way of defining Eclipse launch configurations in a human readable textual form. This improves maintainability and eases versioning/merging of launch configurations.</td>
	<td>Eclipse Public License 1.0</td>
	<td>Eclipse IDE</td>
	<td>Markus Duft</td>
</tr>
```

If the description is too long, just skip the second sentence ;)

**Comment by miklossy** [comment]
Thank you @mduft !

**Comment by miklossy** [comment]
The `Launch Configuration DSL (LcDsl)` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
